USE [master]
GO
/****** Object:  Database [NewsLetterExercise]    Script Date: 16/06/2023 16:43:04 ******/
CREATE DATABASE [NewsLetterExercise]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewsLetterExercise', FILENAME = N'C:\Users\marti\NewsLetterExercise.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewsLetterExercise_log', FILENAME = N'C:\Users\marti\NewsLetterExercise_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [NewsLetterExercise] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewsLetterExercise].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NewsLetterExercise] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET ARITHABORT OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NewsLetterExercise] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NewsLetterExercise] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NewsLetterExercise] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NewsLetterExercise] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [NewsLetterExercise] SET  MULTI_USER 
GO
ALTER DATABASE [NewsLetterExercise] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NewsLetterExercise] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NewsLetterExercise] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NewsLetterExercise] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NewsLetterExercise] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NewsLetterExercise] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [NewsLetterExercise] SET QUERY_STORE = OFF
GO
USE [NewsLetterExercise]
GO
/****** Object:  Table [dbo].[Subscription]    Script Date: 16/06/2023 16:43:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Subscription](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[ConfirmationCode] [uniqueidentifier] NOT NULL,
	[IsConfirmed] [bit] NOT NULL,
 CONSTRAINT [PK_Subscription] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [NewsLetterExercise] SET  READ_WRITE 
GO